### ISSUE TITLE
Filter box in specified container disappears when hiding another column

### ISSUE THREAD

**Issue by 1nickt** [vedmack/yadcf#271]
Hello,

Unfortunately the fix to [colVis + stateSave leads to broken filters #265](https://github.com/vedmack/yadcf/issues/265) hasn't addressed a related issue.

When you use fixedColumns extension, DataTables makes a clone of the first column and displays it over the top of the original table.

You can use yadcf's 'filter_container_id' option to get around this, so long as you intervene and assign an ID to the cloned table's `<th>`. This works nicely.

But if you then use colVis to hide *other* columns, the Filter Box for the fixed column disappears, and does not come back when you unhide the other column.

Refreshing the page  makes the Filter Box appear again.

Please see [this example](http://live.datatables.net/kitawawo/11/edit)

Thank you!

**Comment by 1nickt** [comment]
Happy New Year!

Was wondering if there's any chance you could look at this, or if there's anything else I can do to help?

Thankyou!

**Comment by vedmack** [comment]
Hi,
Thanks,
Fixed headers have no events to listen to so its hard to integrate with it, but a while ago I thought about a way to handle it afterall - to add `filter_container_selector` to yadcf and to point it to the cloned column container, anyway I just comitted several fixes and it seems to work now (its not 100% but it might be in the right direction), [see working jsbin](http://live.datatables.net/ginibiza/1/edit)

**Comment by 1nickt** [comment]
Hi Daniel,

This version improves on the orig as follows:

When you hide a different column, the fixed column's filter box still
disappears. When you re-show the other column, the fixed column's filter
box does NOT reappear.

However, if you then hide and then re-show the fixed column, the filter box
reappears at that point.

Thanks,

Nick

**Comment by 1nickt** [comment]
Hi Daniel,

This jsbin version seems to not have the colvis buttons set ... I will play
with it some more tonight but right now it doesn't show the buttons so I
can;t test the fix.

Thanks,

Nick

**Comment by 1nickt** [comment]
Hi Daniel,

Unfortunately the jsbin referenced above doesn't work ... the fixed col's filter box still disappears and still won't return when I hide/show a different column ...

Let me know if I can help test or anything.

Thanks,
-nick

**Comment by vedmack** [comment]
Should work now, grab the lateset version [0.8.9.beta.37](https://github.com/vedmack/yadcf/blob/999fc40ad1c24ed2b1349decc0edbef9d11b56a6/jquery.dataTables.yadcf.js).

[See jsbin](http://live.datatables.net/ginibiza/7/edit)

**Comment by 1nickt** [comment]
Hi Daniel,

Thanks so much for your work on this.

Unfortunately it's still not working. The jsbin works OK, but since I am building the table from javascript, I can't assign the class to the appropriate table header until after DataTables has cerated the table and then cloned it for the Fixed Column.

This is how I can get a YADFC filter box in the first column, which is fixed, when the table data source is javascript  (unfortunately DataTables just assigns the class, not an id, to the cloned table, so first we have to find it and give it an id so we can add the span to it that YADFC will use):
```
                 // Assign an ID to the cloned table used for the fixedColumn
                  var clonedTable = document.querySelectorAll('.DTFC_Cloned');
                  for (var i = 0; i < clonedTable.length; i++)
                      clonedTable[i].id = 'DTFC_Cloned';

                  $('#DTFC_Cloned thead th:last-child').append(
                      '<span id="my_filter_container" class="my-filter-container"></span>'
                  );

                  yadcf.init(myTable, [
                      {
                          column_number:             0,
                          filter_type:               'text',
                          filter_container_id:       'my_filter_container',
                          filter_reset_button_text:  false,
                          filter_delay:              150,
                      },
```

Now I added a line as in your latest jsbin :
```
                  yadcf.init(myTable, [
                      {
                          column_number:             0,
                          filter_type:               'text',
                          filter_container_id:       'my_filter_container',
                          filter_container_selector: '.DTFC_LeftHeadWrapper .my-filter-container',
                          filter_reset_button_text:  false,
                          filter_delay:              150,
                      },
```

Unfortunately same result; the filter box in the fixed column disappears when you hide another column.

Thanks

- nick
