### ISSUE TITLE
multi_select not working "The select2('close') method was called on an element that is not using Select2."

### ISSUE THREAD

**Issue by wuxinli1025** [vedmack/yadcf#500]
Thank you for your wonderful work!

I'm just having an issue with multi_select's select2 type. the columns are just strings, it gives me 4 errors in the following order after I click on the filter:

1. The select2('close') method was called on an element that is not using Select2.
2. Uncaught TypeError: Cannot read property 'close' of undefined
3. The select2('close') method was called on an element that is not using Select2.
4. Uncaught TypeError: Cannot read property 'close' of undefined

Note, I only clicked on the filter in the header once. If I click it again, it gives me another 4 errors in the above order. Selec2 is already included before yadcf.

Regards,
X

**Comment by vedmack** [comment]
You are welcome,

Please provide a simple test page (jsfiddle)

**Comment by pcapp2114** [comment]
@vedmack Should I post a new question? Paul

**Comment by vedmack** [comment]
@pcapp2114 , no need in opening a new one

**Comment by Wouter8** [comment]
I think this is it.
https://jsfiddle.net/xpvt214o/1005405/

**Comment by vedmack** [comment]
@Wouter8 
404
That page doesn't exist.

**Comment by Wouter8** [comment]
I'm sorry. I thought it already saved when that link was in my URL bar.

This one should work: https://jsfiddle.net/oty1dewr/
@vedmack

**Comment by Wouter8** [comment]
@vedmack could you update me if you made any progress to fixing this? I'm currently buildling something for production and the scroller functionality is needed to keep the site responsive.

**Comment by vedmack** [comment]
@Wouter8 @pcapp2114 , this was a small issue... already fixed in 0.9.4.beta.12 , until I release it you can grab it from my dropbox [temp ](https://www.dropbox.com/s/gkfle5teru0pwi5/tmp12.js?dl=0)file

**Comment by pcapp2114** [comment]
@Wouter8 In your example I see the error when the page first loads. I did not have to click a filter. I disabled the scroller in my example but I still get the same close method error I had before. I placed the Select2 CDN above the Yadcf CDN. https://jsfiddle.net/Paul2167/zusvc4ra/

**Comment by vedmack** [comment]
@Wouter8 @pcapp2114 its aready fixed, see my previous comment and attached link

**Comment by Wouter8** [comment]
@Wouter8  Thanks, gonna try it out right away. Thanks for the quick fix. Amazing! :)

**Comment by Wouter8** [comment]
Working like a charm. I think this can be closed.

**Comment by pcapp2114** [comment]
@vedmack Thank you. Yes 0.9.4.beta.12 Fixes the error for select2('close') method. I tested it. Is it possible to add this to jsfiddle? It only allows CDN's I don't see a way to add a custom js file.

**Comment by pcapp2114** [comment]
I also enabled the scroller with the new beta 12. I don't have the other error. TypeError: Cannot read property 'appendChild' of undefined. Nice work. Thank you @vedmack

**Comment by vedmack** [comment]
fixed in [ 0.9.4.beta.12](https://github.com/vedmack/yadcf/blob/b1b37f48f216fbbc916f8daa2547f13019dbdb0c/src/jquery.dataTables.yadcf.js), npm version published too
